 /* ============================================================================
 Name        : Lab7.c
 Author      : Austin Tian
 Revised by  : Naman Pal
 Version     : 1.0
 Copyright   : Copyright 2023
 Description : Lab 7 in C, ANSI-C Style
 ============================================================================*/

#include "header.h"

// Menu for the testing.
char *menu =    "\n" \
                " ***********Please select the following options**********************\n" \
                " *    This is the memory operation menu (Lab 7)                     *\n" \
                " ********************************************************************\n" \
                " *    1. Write a double-word (32-bit) to the memory                 *\n" \
                " ********************************************************************\n" \
                " *    2. Read a byte (8-bit) data from the memory                   *\n" \
                " *    3. Read a double-word (32-bit) data from the memory           *\n" \
                " ********************************************************************\n" \
                " *    4. Generate a memory dump from any memory location            *\n" \
                " ********************************************************************\n" \
                " *    e. To Exit, Type 'e'  or 'E'                                  *\n" \
                " ********************************************************************\n";

// Generate a random number between 0x00 and 0xFF.
unsigned char rand_generator()
{
    return rand()%255;  // generate a random number between 0 and 255.
}

// Free memory after use to avoid memory leakage.
void free_memory(char *base_address)
{
    free(base_address);
    return;
}

// Complete this function to initialize each memory location with a random number.
char *init_memory()
{
    char *mem = (char *)malloc(MEM_SIZE);  // allocate the memory
    // Start filling in the memory contents with random numbers generated by rand_generator()

    for (int i = 0; i < MEM_SIZE; i++) {
        mem[i] = 0;
    }

    return mem;

}

// Complete this function to store a double word into a memory location
// specified by an address, given by (base_address + offset).
void write_dword(const char *base_address, const int offset, const unsigned int dword_data)
{
    // Step 2: Write a double-word to address: "base_address + offset".
    // Cast the base address to a pointer of unsigned int
    unsigned int *target_address = (unsigned int *)(base_address + offset);

    // Store the double-word at the calculated address
    *target_address = dword_data;

}

// Complete this function to read a byte from a memory location
unsigned char read_byte(const char *base_address, const int offset)
{
    // Step 3: return and print the byte from address: "base_address + offset".

    // Cast the base address to a pointer of unsigned char (1 byte)
    unsigned char target_address = *(unsigned char *)(base_address + offset);
    printf("Byte read %x is: %02x\n", offset, target_address);

    // Read the byte at the calculated address
    //unsigned char byte_read = *target_address;

    return target_address;

}

// Complete this function to read a double word from a memory location
unsigned int read_dword(const char *base_address, const int offset)
{
    // Step 4: return and print the double-word from address: "base_address + offset".

    unsigned int dword = *(unsigned int *)(base_address + offset);
        printf("Double-word at offset %x is: %08x\n", offset, dword);
        return dword;
    // Read the double-word at the calculated address
    //unsigned int dword_read = *target_address;

    // Printing the double word read
    //printf("Double-word read: %u\n", target_address);
    //return target_address;

}

// Complete this function to generate a memory dump.
void memory_dump(const char *base_address, const int offset, unsigned int dumpsize)
{
    // Step 5: Generate a memory dump display starting from address "base_address + offset".
    //        i.e., Display the contents of dump_size bytes starting from  "base_address + offset"
    //        dump_size should be a parameter.
    //        The memory dump display should be similar to the screenshot on the lab manual.

    if (dumpsize < MIN_DUMP_SIZE || dumpsize > MEM_SIZE)
        dumpsize = MIN_DUMP_SIZE;  // make sure the min dump size is 256

    const unsigned char *start_address = (const unsigned char *)(base_address + offset);    // from where the dump starts

    for (unsigned int i = 0; i < dumpsize; i += 16) {   // print ends at dumpsize
        printf("%p: ", start_address + i); // Print the memory address

        // Print hexadecimal values
        for (int j = 0; j < 16; j++) {
            if (i + j < dumpsize) {
                printf("%02X ", start_address[i + j]);
            } else {
                printf("   "); // If end of dump is reached, print spaces for alignment
            }

            if (j % 8 == 7) {
                printf(" "); // Extra space after 8 bytes for better formatting
            }
        }

        printf(" | ");

        // Print ASCII representation
        for (unsigned int j = 0; j < 16; j++) {
            if (i + j < dumpsize) {
                unsigned char current_byte = start_address[i + j];
                if (current_byte >= 32 && current_byte <= 126) {
                    printf("%c", current_byte); // Display printable ASCII characters
                } else {
                    printf("."); // Display non-printable characters as '.'
                }
            } else {
                printf(" "); // If end of dump is reached, print spaces for alignment
            }
        }

        printf("\n");
    }
}

// This is a memory controller you can use to test your memory system.
void setup_memory()
{
    // Now we need to setup the memory controller for the computer system we
    // will build. Basic requirements:
    // 1. Memory size needs to be 1M Bytes
    // 2. Memory is readable/writable with Byte and Double-Word Operations.
    // 3. Memory can be dumped and shown on screen.
    // 4. Memory needs to be freed (released) at the end of the code.
    // 6. For lab 7, we need to have a user interface to fill in memory,
    //                                      read memory and do memory dump.

                puts("Hey, this worked");  // output base memory first.

    char *mem = init_memory();  // initialize the memory.
    char options =0;
    unsigned int offset, dumpsize;
    char tempchar;
    unsigned int dword_data;      // 32-bit operation.
    do{
        if (options != 0x0a)  // if options has a return key input, skip it.
        {
            puts(menu); /* prints Memory Simulation */
            printf ("\nThe base address of your memory is: %I64Xh (HEX)\n", (long long unsigned int)(mem));  // output base memory first.
            puts("Please make a selection:");  // output base memory first.
        }
            options = getchar();

            switch (options)
            {
                case '1':  // write double word.
                    puts("Please input your memory's offset address (in HEX):");
                    scanf("%x", (unsigned int*)&offset);    // input an offset address (in HEX) to write.
                    puts("Please input your DOUBLE WORD data to be written (in HEX):");
                    scanf("%x", (unsigned int*)&dword_data);    // input data
                    write_dword (mem, offset, dword_data);  // write a double word to memory.
                    continue;
                case '2':  // read byte.
                    puts("Please input your memory's offset address (in HEX):");
                    scanf("%x", &offset);    // input an offset address (in HEX) to write.
                    read_byte(mem, offset);
                    continue;
                case '3':  // read double word.
                    puts("Please input your memory's offset address (in HEX):");
                    scanf("%x", &offset);    // input an offset address (in HEX) to write.
                    read_dword(mem, offset);
                    continue;
                case '4':  // generate memory dump starting at offset address (in HEX).
                    puts("Please input your memory's offset address (in HEX, should be a multiple of 0x10h):");
                    scanf("%x", &offset);    // input an offset address (in HEX) to start.
                    puts("Please input the size of the memory to be dumped (a number between 256 and 1024 ):");
                    scanf("%d", &dumpsize);    // The size of the memory dump
                    memory_dump(mem, offset, dumpsize);  // generate a memory dump display of dumpsize bytes.
                    continue;
                case 'e':
                case 'E':
                    puts("Code finished, press any key to exit");
                    free_memory(mem);
                    while ((tempchar = getchar()) != '\n' && tempchar != EOF);  // wait for the enter.
                    tempchar = getchar();
                    return;  // return to main program.
                default:
                    // puts("Not a valid entry, please try again");
                    continue;
            }
    }while (1);  // make sure the only exit is from 'e'.
    return;
}
